# -*- coding: utf-8 -*-
# Problems referenced as variants on a card back but not in the deck.
# lc -> (official title, LeetCode slug). The app lists them in the menu with links.
VARIANTS = {
    15: ('3Sum', '3sum'),
    42: ('Trapping Rain Water', 'trapping-rain-water'),
    81: ('Search in Rotated Sorted Array II', 'search-in-rotated-sorted-array-ii'),
    84: ('Largest Rectangle in Histogram', 'largest-rectangle-in-histogram'),
    91: ('Decode Ways', 'decode-ways'),
    140: ('Word Break II', 'word-break-ii'),
    150: ('Evaluate Reverse Polish Notation', 'evaluate-reverse-polish-notation'),
    153: ('Find Minimum in Rotated Sorted Array', 'find-minimum-in-rotated-sorted-array'),
    159: ('Longest Substring with At Most Two Distinct Characters', 'longest-substring-with-at-most-two-distinct-characters'),
    167: ('Two Sum II - Input Array Is Sorted', 'two-sum-ii-input-array-is-sorted'),
    210: ('Course Schedule II', 'course-schedule-ii'),
    224: ('Basic Calculator', 'basic-calculator'),
    235: ('Lowest Common Ancestor of a Binary Search Tree', 'lowest-common-ancestor-of-a-binary-search-tree'),
    242: ('Valid Anagram', 'valid-anagram'),
    269: ('Alien Dictionary', 'alien-dictionary'),
    340: ('Longest Substring with At Most K Distinct Characters', 'longest-substring-with-at-most-k-distinct-characters'),
    424: ('Longest Repeating Char Replacement', 'longest-repeating-character-replacement'),
    438: ('Find All Anagrams in a String', 'find-all-anagrams-in-a-string'),
    472: ('Concatenated Words', 'concatenated-words'),
    523: ('Continuous Subarray Sum', 'continuous-subarray-sum'),
    525: ('Contiguous Array', 'contiguous-array'),
    543: ('Diameter of Binary Tree', 'diameter-of-binary-tree'),
    653: ('Two Sum IV - Input is a BST', 'two-sum-iv-input-is-a-bst'),
    687: ('Longest Univalue Path', 'longest-univalue-path'),
    772: ('Basic Calculator III', 'basic-calculator-iii'),
    852: ('Peak Index in a Mountain Array', 'peak-index-in-a-mountain-array'),
    953: ('Verifying an Alien Dictionary', 'verifying-an-alien-dictionary'),
    974: ('Subarray Sums Divisible by K', 'subarray-sums-divisible-by-k'),
    1004: ('Max Consecutive Ones III', 'max-consecutive-ones-iii'),
    1095: ('Find in Mountain Array', 'find-in-mountain-array'),
    1123: ('Lowest Common Ancestor of Deepest Leaves', 'lowest-common-ancestor-of-deepest-leaves'),
    1136: ('Parallel Courses', 'parallel-courses'),
    1372: ('Longest ZigZag Path in a Binary Tree', 'longest-zigzag-path-in-a-binary-tree'),
    1650: ('Lowest Common Ancestor of a Binary Tree III', 'lowest-common-ancestor-of-a-binary-tree-iii'),
    1793: ('Maximum Score of a Good Subarray', 'maximum-score-of-a-good-subarray'),
}
